supermaker/apps/sp_goods/urls.py
from django.conf.urls import url

from sp_goods.views import (IndexView, DetailView, CollectView,
                            CollectEditView, ShopcartView, TrueorderView,
                             CategoryView)

urlpatterns = [

    url(r'^index/$', IndexView.as_view(), name='index'),  # 首页   as_view 后面有()
    url(r'^detail/(?P<sku_id>\d+)/$', DetailView.as_view(), name='detail'),  # 详情
    url(r'^collect/$', CollectView.as_view(), name='collect'),  # 收藏
    url(r'^collect_edit/$', CollectEditView.as_view(), name='collect-edit'),  # 收藏编辑
    url(r'^shopcart/$', ShopcartView.as_view(), name='shopcart'),  # 加入购物车
    url(r'^trueorder/$', TrueorderView.as_view(), name='trueorder'),  # 立即购买
    url(r'^category/$', CategoryView.as_view(), name='category'),  # 商品分类

]

supermaker/apps/sp_user/urls.py
from django.conf.urls import url

from sp_user.views import (RegisterView,
                           LoginView,
                           CenterView,
                           InfoView,
                           )

urlpatterns = [
    url(r'^register/$', RegisterView.as_view(), name='register'),  # 注册
    url(r'^login/$', LoginView.as_view(), name='login'),  # 登录
    url(r'^center/$', CenterView.as_view(), name='center'),  # 个人中心
    url(r'^info/$', InfoView.as_view(), name='info'),  # 个人资料
]

supermaker/supermaker/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # 上传部件自动调用的上传地址
    url(r'^ckeditor/', include("ckeditor_uploader.urls")),
    # 用户
    url(r'^user/', include("sp_user.urls", namespace="sp_user")),
    # 商城
    url(r'^sp_goods/', include("sp_goods.urls", namespace="sp_goods")),
]

supermaker/apps/sp_goods/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models

# Create your models here.
from db.base_model import BaseModel


class GoodsSKU(BaseModel):
    """
    商品SKU表(多)  :  商品名 简介 价格 (单位 (id)) 库存 销量
                      LOGO地址 是否上架 (商品分类ID) (商品spu_id)
    """
    is_on_choice = (
        (0, '上架'),
        (1, '下架')
    )
    sku_name = models.CharField(verbose_name='sku名称', max_length=100, )
    brief = models.CharField(verbose_name='商品简介',
                             max_length=200,
                             null=True,
                             blank=True
                             )
    price = models.DecimalField(verbose_name='商品价格',
                                max_digits=9,  # 总长度
                                decimal_places=2,  # 小数位数是两位
                                default=0
                                )
    unit = models.ForeignKey(to="GoodsUnit", verbose_name='单位')
    stock = models.IntegerField(verbose_name='库存', default=0)
    sale_num = models.IntegerField(verbose_name='销量', default=0)
    logo = models.ImageField(
        verbose_name='封面图片',
        upload_to='goods/%Y%m/%d'
    )
    is_on_sale = models.BooleanField(verbose_name='是否上架',
                                     default=0,
                                     choices=is_on_choice
                                     )
    category = models.ForeignKey(to="GoodsCategory", verbose_name='商品分类')
    goods_spu = models.ForeignKey(to="GoodsSPU", verbose_name="商品spu ID")

    class Meta:
        verbose_name = '商品SKU管理'
        verbose_name_plural = verbose_name


class GoodsCategory(BaseModel):
    """
    商品分类表(一)  :  分类名,分类简介
    """
    cate_name = models.CharField(max_length=20, verbose_name='商品名称')
    brief = models.CharField(null=True,
                             blank=True,
                             max_length=200,
                             verbose_name='商品描述'
                             )

    def __str__(self):
        return self.cate_name

    class Meta:
        verbose_name = '商品分类管理'
        verbose_name_plural = verbose_name


class GoodsSPU(models.Model):
    """
    商品SPU表,不用写添加时间等 : 名称,详情
    """
    spu_name = models.CharField(max_length=20, verbose_name='商品SPU名称')
    # content = models.TextField(verbose_name='商品详情')
    content = RichTextUploadingField(verbose_name="商品详情")



    def __str__(self):
        return self.spu_name

    class Meta:
        verbose_name = '商品SPU管理'
        verbose_name_plural = verbose_name


class GoodsGallery(BaseModel):
    """
    商品相册表  :  图片地址,商品ID(保存了SKU中的id)
    """
    img_url = models.ImageField(verbose_name="图片地址",
                                upload_to='goods_gallery/%Y%m/%d'
                                )
    goods_sku = models.ForeignKey(to="GoodsSKU",
                                  verbose_name="SKU商品")

    class Meta:
        verbose_name = '商品相册管理'
        verbose_name_plural = verbose_name


class GoodsUnit(BaseModel):
    """
    商品单位表  :  单位名(斤,箱)
    """
    name = models.CharField(max_length=20, verbose_name='单位')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '商品单位管理'
        verbose_name_plural = verbose_name

class Banner(BaseModel):
    """
    首页轮播
        后台设置首页轮播图片和关联商品
        前台展示
        点击轮播图片进入到商品详情
    """
    name = models.CharField(verbose_name="轮播活动名",
                           max_length=150
                            )
    goods_sku =models.ForeignKey(to='GoodsSKU',verbose_name='商品sku ')

    ban_img =models.ImageField(verbose_name='轮播图片',
                               upload_to='ban/%Y%m/%d'
                               )
    order = models.SmallIntegerField(verbose_name='排序',
                                     default=0
                                     )
    class Meta:
        verbose_name = '首页轮播图管理'
        verbose_name_plural=verbose_name

    def __str__(self):
        return self.name

class Activity(BaseModel):
    """
        首页活动
    """
    title = models.CharField(verbose_name='活动名称',
                             max_length=150
                             )
    img_url =models.ImageField(verbose_name='活动图片',
                               upload_to='activity/%Y%m/%d'
                               )
    url_site = models.CharField(verbose_name='活动的url地址', max_length=200)

    class Meta:
        verbose_name='首页活动管理'
        verbose_name_plural=verbose_name

    def __str__(self):
        return self.title

class ActivityZone(BaseModel):
    """
        首页活动专区
    """
    is_on_choice = (
        (0, '上架'),
        (1, '下架')
    )
    title = models.CharField(verbose_name='活动专区名称', max_length=150)
    brief = models.CharField(verbose_name="活动专区的简介",
                             max_length=200,
                             null=True,
                             blank=True,
                             )
    order = models.SmallIntegerField(verbose_name="排序",
                                     default=0,
                                     )
    is_on_sale = models.BooleanField(verbose_name="上否上线",
                                     choices=is_on_choice,
                                     default=0,
                                     )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "活动专区管理"
        verbose_name_plural = verbose_name


class ActivityZoneGoods(BaseModel):
    """
        首页活动专区商品列表
    """
    activity_zone = models.ForeignKey(to="ActivityZone",
                                      verbose_name="活动专区ID",
                                      )
    goods_sku = models.ForeignKey(to="GoodsSKU",
                                  verbose_name="专区商品SKU_ID",
                                  )

supermaker/apps/sp_goods/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse
from django.views import View

from sp_goods.models import GoodsCategory, GoodsSKU


class CategoryView(View):
    def get(self, request):
        categorys = GoodsCategory.objects.filter(is_delete=False)
        goods_sku = GoodsSKU.objects.filter(is_delete=False)

        context = {
            'categorys': categorys,
            'goods_sku': goods_sku
        }
        return render(request, 'sp_goods/category.html', context)

    def post(self, request):
        pass


class IndexView(View):
    def get(self, request):
        goods_sku = GoodsSKU.objects.filter(is_delete=False)
        context = {
            'goods_sku': goods_sku
        }

        return render(request, 'sp_goods/index.html', context)

    def post(self, request):
        pass


class DetailView(View):
    def get(self, request, sku_id):
        # 接收数据
        try:
            sku_id = int(sku_id)
            # 处理数据
            goods_sku = GoodsSKU.objects.get(pk=sku_id)
            # 响应
            context = {
                "goods_sku": goods_sku
            }

            return render(request, 'sp_goods/detail.html', context)
        except:
            return redirect(reverse('sp_goods:index'))

    def post(self, request):
        pass


class CollectView(View):
    def get(self, request):
        return render(request, 'sp_goods/collect.html')

    def post(self, request):
        pass


class CollectEditView(View):
    def get(self, request):
        return render(request, 'sp_goods/collect-edit.html')

    def post(self, request):
        pass


class ShopcartView(View):
    def get(self, request):
        return render(request, 'sp_goods/shopcart.html')

    def post(self, request):
        pass


class TrueorderView(View):
    def get(self, request):
        return render(request, 'sp_goods/tureorder.html')

    def post(self, request):
        pass

supermaker/templates/sp_goods/category.html
{% extends 'public/base.html' %}
{% load static %}
{% block meta_css %}
    <style>
        .shop-list-mid .tit a {
            color: #909090;
            font-size: 1.4rem;
            display: -webkit-box;
            -webkit-line-clamp: 1;
            -webkit-box-orient: vertical;
            overflow: hidden;
            white-space: normal;
            text-overflow: ellipsis;
        }
    </style>
{% endblock %}

{% block content_nav %}
    <header data-am-widget="header" class="am-header am-header-default sq-head ">
        <div class="am-header-left am-header-nav">
            <a href="javascript:history.back()" class="">
                <i class="am-icon-chevron-left"></i>
            </a>
        </div>
        <div class="cate-search">
            <input type="text" class="cate-input" placeholder="请输入您要的搜索的产品关键词"/>
            <input type="button" class="cate-btn"/>
        </div>
    </header>

{% endblock %}

{% block content_main %}
    <div style="height: 49px;"></div>
    <ul class="list-nav">
        <li class="current"><a href="">综合</a></li>
        <li><a href="">销量</a></li>
        <li><a href=""><i class="list-price">价格</i></li>
        <li><a href="">新品</a></li>
    </ul>
    <div class="content-list">
        <div class="list-left">
            {% for category in categorys %}
                <li class="current">
                    <a href="">{{ category.cate_name }}</a></li>
            {% endfor %}
        </div>
        <div class="list-right">
            <ul class="list-pro">
                {% for goods in goods_sku %}
                    <li>
                        <a href="{% url 'sp_goods:detail' goods.pk %}"><img src=" {{ MEDIA_URL }}{{ goods.logo }}" class="list-pic"/></a>
                        <div class="shop-list-mid" style="width: 65%;">
                            <div class="tit">
                                <a href="detail.html">
                                    {{ goods.goods_spu.spu_name }}&emsp;{{ goods.sku_name }}
                                </a></div>
                            <div class="am-gallery-desc">￥{{ goods.price }}</div>
                            <p>销量：{{ goods.sale_num }}{{ goods.unit }}</p>
                        </div>
                        <div class="list-cart">
                            <div class="d-stock ">
                                <a class="decrease">-</a>
                                <input id="num" readonly="" class="text_box" name="" type="text" value="0">
                                <a class="increase">+</a>
                            </div>
                        </div>
                        <!--<a href="" class="list-cart"><img src="images/cart.png" width="30"/></a>-->
                    </li>
                {% endfor %}


            </ul>
        </div>
    </div>

    <!--底部-->
    <div style="height: 55px;"></div>
    <div class="fix-bot">
        <div class="fix-bot-cart"><i>8</i></div>
        <a href="tureorder.html" class="list-js">去结算</a>
        <a href="tureorder.html" class="list-jsk">一键快购</a>
        <!--<div class="js-text">
           <p><b>￥217.80</b></p>
           <p class="js-car">购物满50元免运费</p>
     </div>-->
    </div>
{% endblock %}

{% block footer_js %}

    <script>
        //购物数量加减
        $(function () {
            $('.increase').click(function () {
                var self = $(this);
                var current_num = parseInt(self.siblings('input').val());
                current_num += 1;
                if (current_num > 0) {
                    self.siblings(".decrease").fadeIn();
                    self.siblings(".text_box").fadeIn();
                }
                self.siblings('input').val(current_num);
                update_item(self.siblings('input').data('item-id'));
            })
            $('.decrease').click(function () {
                var self = $(this);
                var current_num = parseInt(self.siblings('input').val());
                if (current_num > 0) {
                    current_num -= 1;
                    if (current_num < 1) {
                        self.fadeOut();
                        self.siblings(".text_box").fadeOut();
                    }
                    self.siblings('input').val(current_num);
                    update_item(self.siblings('input').data('item-id'));
                }
            })
        })

    </script>
{% endblock %}

supermaker/templates/sp_goods/collect.html
{% extends 'public/base.html' %}
{% load static %}
	{% block content_main %}
        <body>
		<header data-am-widget="header" class="am-header am-header-default sq-head ">
			<div class="am-header-left am-header-nav">
				<a href="javascript:history.back()" class="">
					<i class="am-icon-chevron-left"></i>
				</a>
			</div>
			<h1 class="am-header-title">
  	            <a href="" class="">我的收藏</a>
            </h1>
            <div class="am-header-right am-header-nav">
                    <a href="{% url 'sp_goods:collect-edit' %}" class="">
		        编辑
		        </a>
			</div>
	    </header>
	    <div style="height: 49px;"></div>
	   <ul class="list-pro" style="margin-top: 0;">
	    	<li>
	    		<a href="detail.html"><img src=" {% static 'images/test10.png' %}" class="list-pic" /></a>
	    		<div class="shop-list-mid" style="width: 65%;">
                	<div class="tit"><a href="detail.html">法国加力果12个装 进口新鲜水果 嘎啦苹果 包邮</a></div>
                	<div class="am-gallery-desc">￥52</div>
                	<p>销量：5件</p>
                </div>
                <div class="list-cart">
	                <div class="d-stock ">
			                <a class="decrease">-</a>
			                <input id="num" readonly="" class="text_box" name="" type="text" value="0">
			                <a class="increase">+</a>
	                </div>
                </div>
                <!--<a href="" class="list-cart"><img src="images/cart.png" width="30"/></a>-->
	    	</li>
	    	<li>
	    		<a href="detail.html"><img src=" {% static 'images/test10.png' %}" class="list-pic" /></a>
	    		<div class="shop-list-mid" style="width: 65%;">
                	<div class="tit"><a href="detail.html">法国加力果12个装 进口新鲜水果 嘎啦苹果 包邮</a></div>
                	<div class="am-gallery-desc">￥52</div>
                	<p>销量：5件</p>
                </div>
                <div class="list-cart">
                <div class="d-stock ">
		                <a class="decrease">-</a>
		                <input id="num" readonly="" class="text_box" name="" type="text" value="0">
		                <a class="increase">+</a>
                </div>
                </div>
                <!--<a href="" class="list-cart"><img src="images/cart.png" width="30"/></a>-->
	    	</li>
	    	<li>
	    		<a href="detail.html"><img src="{% static 'images/test10.png' %}" class="list-pic" /></a>
	    		<div class="shop-list-mid" style="width: 65%;">
                	<div class="tit"><a href="detail.html">法国加力果12个装 进口新鲜水果 嘎啦苹果 包邮</a></div>
                	<div class="am-gallery-desc">￥52</div>
                	<p>销量：5件</p>
                </div>
                <div class="list-cart">
                <div class="d-stock ">
		                <a class="decrease">-</a>
		                <input id="num" readonly="" class="text_box" name="" type="text" value="0">
		                <a class="increase">+</a>
                </div>
                </div>
                <!--<a href="" class="list-cart"><img src="images/cart.png" width="30"/></a>-->
	    	</li>
	    	<li>
	    		<a href="detail.html"><img src=" {% static 'images/test10.png' %}" class="list-pic" /></a>
	    		<div class="shop-list-mid" style="width: 65%;">
                	<div class="tit"><a href="detail.html">法国加力果12个装 进口新鲜水果 嘎啦苹果 包邮</a></div>
                	<div class="am-gallery-desc">￥52</div>
                	<p>销量：5件</p>
                </div>
                <div class="list-cart">
                <div class="d-stock ">
		                <a class="decrease">-</a>
		                <input id="num" readonly="" class="text_box" name="" type="text" value="0">
		                <a class="increase">+</a>
                </div>
                </div>
                <!--<a href="" class="list-cart"><img src="images/cart.png" width="30"/></a>-->
	    	</li>
	    	<li>
	    		<a href="detail.html"><img src=" {% static 'images/test10.png' %}" class="list-pic" /></a>
	    		<div class="shop-list-mid" style="width: 65%;">
                	<div class="tit"><a href="detail.html">法国加力果12个装 进口新鲜水果 嘎啦苹果 包邮</a></div>
                	<div class="am-gallery-desc">￥52</div>
                	<p>销量：5件</p>
                </div>
                <div class="list-cart">
                <div class="d-stock ">
		                <a class="decrease">-</a>
		                <input id="num" readonly="" class="text_box" name="" type="text" value="0">
		                <a class="increase">+</a>
                </div>
                </div>
                <!--<a href="" class="list-cart"><img src="images/cart.png" width="30"/></a>-->
	    	</li>
	    	<li>
	    		<a href="detail.html"><img src="{% static 'images/test10.png' %}" class="list-pic" /></a>
	    		<div class="shop-list-mid" style="width: 65%;">
                	<div class="tit"><a href="detail.html">法国加力果12个装 进口新鲜水果 嘎啦苹果 包邮</a></div>
                	<div class="am-gallery-desc">￥52</div>
                	<p>销量：5件</p>
                </div>
                <div class="list-cart">
                <div class="d-stock ">
		                <a class="decrease">-</a>
		                <input id="num" readonly="" class="text_box" name="" type="text" value="0">
		                <a class="increase">+</a>
                </div>
                </div>
                <!--<a href="" class="list-cart"><img src="images/cart.png" width="30"/></a>-->
	    	</li>
	    	<li>
	    		<a href="detail.html"><img src=" {% static 'images/test10.png' %}" class="list-pic" /></a>
	    		<div class="shop-list-mid" style="width: 65%;">
                	<div class="tit"><a href="detail.html">法国加力果12个装 进口新鲜水果 嘎啦苹果 包邮</a></div>
                	<div class="am-gallery-desc">￥52</div>
                	<p>销量：5件</p>
                </div>
                <div class="list-cart">
                <div class="d-stock ">
		                <a class="decrease">-</a>
		                <input id="num" readonly="" class="text_box" name="" type="text" value="0">
		                <a class="increase">+</a>
                </div>
                </div>
                <!--<a href="" class="list-cart"><img src="images/cart.png" width="30"/></a>-->
	    	</li>

	    </ul>
	    <!--底部-->
 <div style="height: 55px;"></div>
 <div data-am-widget="navbar" class="am-navbar am-cf am-navbar-default sq-foot am-no-layout" id="">
      <ul class="am-navbar-nav am-cf am-avg-sm-5">
          <li>
            <a href="{% url 'sp_goods:index' %}" class="">
                <span class="am-icon-home"></span>
                <span class="am-navbar-label">首页</span>
            </a>
          </li>
          <li>
            <a href="message.html" class="">
                <span class="am-icon-comments"></span>
                <span class="am-navbar-label">动态</span>
            </a>
          </li>
          <li>
            <a href="shopcart.html" class="">
                <span class="am-icon-shopping-cart"></span>
                <span class="am-navbar-label">购物车</span>
            </a>
          </li>
          <li>
            <a href="allorder.html" class="">
                <span class="am-icon-file-text"></span>
                <span class="am-navbar-label">订单</span>
            </a>
          </li>

          <li>
            <a href="{% url 'sp_user:center' %}" class="curr">
                <span class="am-icon-user"></span>
                <span class="am-navbar-label">我的</span>
            </a>
          </li>
      </ul>
</div>
	{% endblock %}

{% block footer_js %}
    <script>
//购物数量加减
$(function(){
		$('.increase').click(function(){
			var self = $(this);
			var current_num = parseInt(self.siblings('input').val());
			current_num += 1;
			if(current_num > 0){
				self.siblings(".decrease").fadeIn();
				self.siblings(".text_box").fadeIn();
			}
			self.siblings('input').val(current_num);
			update_item(self.siblings('input').data('item-id'));
		})
		$('.decrease').click(function(){
			var self = $(this);
			var current_num = parseInt(self.siblings('input').val());
			if(current_num > 0){
				current_num -= 1;
                if(current_num < 1){
	                self.fadeOut();
					self.siblings(".text_box").fadeOut();
                }
				self.siblings('input').val(current_num);
				update_item(self.siblings('input').data('item-id'));
			}
		})
	})

</script>
{% endblock %}

supermaker/templates/sp_goods/detail.html
{% extends 'public/base_nav.html' %}
{% load static %}
{% block meta_css %}
    <script>
        function changeImage() {
            document.getElementById("imgflag").src = "images/redherat.png";
        }
    </script>
    <style>
        .am-slider-default .am-control-nav {
            text-align: center;
        }

        .am-slider-default .am-control-nav li a.am-active {
            background: #cb2527;
        }

        .am-slider-default .am-control-nav li a {
            border: 0;
            width: 10px;
            height: 10px;
        }
    </style>
{% endblock %}
{% block content_main %}
    </head>
    <body>
    <header data-am-widget="header" class="am-header am-header-default sq-head ">
        <div class="am-header-left am-header-nav">
            <a href="javascript:history.back()" class="">
                <i class="am-icon-chevron-left"></i>
            </a>
        </div>
        <h1 class="am-header-title">
            <a href="" class="">商品详情</a>
        </h1>
    </header>
    <div style="height: 49px;"></div>
    <!--图片轮换-->
    <div class="am-slider am-slider-default" data-am-flexslider id="demo-slider-0">
        <ul class="am-slides">
            {% for galler in goods_sku.goodsgallery_set.all %}
               <li> <img src="{{ MEDIA_URL }}{{ galler.img_url }}" alt=""></li>
            {% endfor %}
        </ul>
    </div>
    <div class="detal-info" style="position: relative; width: 100%;">
        <p>{{ goods_sku.goods_spu.spu_name }}{{ goods_sku.sku_name }}</p>
        <h2>商城价：<span>￥{{ goods_sku.price }}</span></h2>
        <div class="heart">
            <img src="{% static 'images/herat.png' %}" width="25" id="imgflag" onclick="changeImage()"/>
            <p>收藏</p>
        </div>
    </div>
    <div class="d-amount">
        <h4>数量：</h4>
        <div class="d-stock">
            <a class="decrease">-</a>
            <input id="num" readonly="" class="text_box" name="" type="text" value="1">
            <input id="id" type="hidden" value="644">
            <a class="increase">+</a>
            <span id="dprice" class="price" style="display:none"> 36</span>
        </div>
    </div>
    <div style="background: #eee; height: 10px;"></div>
    <div class="am-tabs detail-list" data-am-tabs>
        <ul class="am-tabs-nav am-nav am-nav-tabs">
            <li class="am-active"><a href="#tab1">商品详情</a></li>
            <li><a href="#tab2">商品评论</a></li>
        </ul>

        <div class="am-tabs-bd">
            <div class="am-tab-panel am-fade am-in am-active detail " id="tab1">
               <p>{{ goods_sku.goods_spu.content|safe }}</p>
                <img src="{{ MEDIA_URL }}{{ goods_sku.logo }}"/>
            </div>
            <div class="am-tab-panel am-fade detail " id="tab2">
                <!--<div class="comment">
                    <span>好评：</span>
                    <div class="com-good"></div>
                    <span>100%</span>
                </div>
                <div class="comment">
                    <span>中评：</span>
                    <div class="com-bad"></div>
                    <span>0%</span>
                </div>
                <div class="comment">
                    <span>差评：</span>
                    <div class="com-bad"></div>
                    <span>0%</span>
                </div>-->
                <ul class="comment-list">
                    <li class="current"><a href="">全部</a></li>
                    <li><a href="">好评（20）</a></li>
                    <li><a href="">中评（5）</a></li>
                    <li><a href="">差评（0）</a></li>
                </ul>
                <ul class="comment-pic">
                    <li>
                        <div class="tit">
                            <img src="{% static 'images/tx.png' %}" class="tx"/>
                            <span>songke2014</span>
                            <i> [2016-01-01]</i>
                        </div>
                        <div class="comment-con">
                            买了些给家人，都说不错！
                        </div>
                    </li>
                    <li>
                        <div class="tit">
                            <img src="{% static 'images/tx.png' %}" class="tx"/>
                            <span>songke2014</span>
                            <i> [2016-01-01]</i>
                        </div>
                        <div class="comment-con">
                            买了些给家人，都说不错！
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>


    <!--底部-->
    <div style=" height: 55px;"></div>
    <ul class="fix-shopping">
        <li><a href="{% url 'sp_goods:shopcart' %}" class="join">加入购物车</a></li>
        <li><a href="{% url 'sp_goods:trueorder' %}" class="imm-buy">立即购买</a></li>
    </ul>

    </body>
    </html>
{% endblock %}

{% block footer_js %}
    <script>
        //购物数量加减
        $(function () {
            $('.increase').click(function () {
                var self = $(this);
                var current_num = parseInt(self.siblings('input').val());
                current_num += 1;
                self.siblings('input').val(current_num);
                update_item(self.siblings('input').data('item-id'));
            })
            $('.decrease').click(function () {
                var self = $(this);
                var current_num = parseInt(self.siblings('input').val());
                if (current_num > 1) {
                    current_num -= 1;
                    self.siblings('input').val(current_num);
                    update_item(self.siblings('input').data('item-id'));
                }
            })
        })
    </script>





{% endblock %}