supermaker/apps/sp_user/urls.py
from django.conf.urls import url

from sp_user.views import (RegisterView,
                           LoginView,
                           CenterView,
                           InfoView,
                           )

urlpatterns = [
    url(r'^register/$', RegisterView.as_view(), name='register'),  # 注册
    url(r'^login/$', LoginView.as_view(), name='login'),  # 登录
    url(r'^center/$', CenterView.as_view(), name='center'),  # 个人中心
    url(r'^info/$', InfoView.as_view(), name='info'),  # 个人资料
]

supermaker/supermaker/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # 上传部件自动调用的上传地址
    url(r'^ckeditor/', include("ckeditor_uploader.urls")),
    # 用户
    url(r'^user/', include("sp_user.urls", namespace="sp_user")),
    # 商城
    url(r'^sp_goods/', include("sp_goods.urls", namespace="sp_goods")),
]

supermaker/apps/sp_user/models.py
from django.db import models
from db.base_model import BaseModel


class User(BaseModel):
    # 用户表
    # 性别选项
    sex_choices = (
        (1, '男'),
        (2, "女"),
        (3, "保密"),
    )
    nickname = models.CharField(verbose_name='昵称',
                                max_length=20,
                                null=True,
                                blank=True,
                                )
    phone = models.CharField(verbose_name='手机号码',

                             max_length=12)
    password = models.CharField(verbose_name='密码',
                                max_length=64,
                                )
    gender = models.SmallIntegerField(verbose_name='性别',
                                      default=3,
                                      choices=sex_choices,
                                      )
    head = models.ImageField(verbose_name='用户头像',
                             upload_to='head/%Y/%m',
                             default='tset/201809/25/tx1.png',
                             )

    birthday = models.DateField(verbose_name='出生日期',
                                null=True,
                                blank=True,
                                )
    school_name = models.CharField(verbose_name='学校名称',
                                   max_length=50,
                                   null=True, blank=True,
                                   )
    address = models.CharField(verbose_name='学校详细地址',
                               max_length=100,
                               null=True,
                               blank=True,
                               )
    hometown = models.CharField(verbose_name='老家',
                                max_length=100,
                                null=True, blank=True,
                                )

    class Meta:
        verbose_name = '用户管理'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.phone

class TestImg(BaseModel):
    img=models.ImageField(verbose_name='图片测试',
                          upload_to='tset/%Y%m/%d'
                          )

supermaker/apps/sp_user/forms.py
from django import forms
from django.core import validators
from sp_user.helper import set_password
from sp_user.models import User


# 注册表单
class RegisterForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # 验证手机号码格式是否正确
        self.fields['phone'].validators.append(validators.RegexValidator(r'^1[3-9]\d{9}$', "手机号码格式错误!"))
        # 密码 在form中要求 6-16 个
        self.fields['password'].validators.append(validators.MinLengthValidator(6))
        self.fields['password'].validators.append(validators.MaxLengthValidator(16))

    class Meta:
        model = User
        # 注册只验证手机和密码
        fields = ['phone', 'password']
        # 错误信息提示
        error_messages = {
            'password': {
                'min_length': "密码长度至少6个字符!",
                'max_length': "密码长度不能大于16个字符!",
                'required': "请填写密码!",
            },
            "phone": {
                "required": "手机号码必须填写!",
            }
        }
        # form字段样式设置
        widgets = {
            "phone": forms.TextInput(attrs={'class': 'login-name', 'placeholder': '请输入手机号'}),
            "password": forms.PasswordInput(attrs={'class': 'login-password', 'placeholder': '请输入密码'}),
        }

    # 检测用户手机是否已经被注册
    def clean_phone(self):
        phone = self.cleaned_data.get('phone')
        rs = User.objects.filter(phone=phone).exists()
        if rs:
            raise forms.ValidationError("该手机号码已经被注册!")
        return phone

    # 综合校验
    def clean(self):
        # 获取所有清洗后的数据
        data = super(RegisterForm, self).clean()

        pwd1 = data.get('password')
        pwd2 = data.get('repassword')
        if pwd1 and pwd2 and pwd1 != pwd2:
            raise forms.ValidationError({'repassword': '两次密码输入不一致!'})
        else:
            # 取密码
            if pwd1:
                # 如果密码不为空 进行加密
                data['password'] = set_password(pwd1)
        return data


# 登陆表单
class LoginForm(forms.ModelForm):
    class Meta:
        model = User
        # 只验证用户手机和密码
        fields = ['phone', 'password']
        # 错误信息
        error_messages = {
            'phone': {
                "required": "手机号码必填!",
            },
            "password": {
                "required": "请填写密码!",
                "min_length": "密码不得少于6个字符!",
                "max_length": "密码不得大于16个字符!",
            }
        }

        # 添加前端样式
        widgets = {
            "phone": forms.TextInput(attrs={'class': 'login-name', 'placeholder': '请输入手机号'}),
            "password": forms.PasswordInput(attrs={'class': 'login-password', 'placeholder': '请输入密码'}),
        }

    def clean(self):
        cleaned_data = super().clean()
        # 验证手机号码是否正确
        phone = cleaned_data.get('phone')
        password = cleaned_data.get('password')

        # 通过手机号码查询数据,再验证密码,没有直接报错
        user = User.objects.filter(phone=phone).first()

        if user is None:
            raise forms.ValidationError({'phone': '该手机没有注册'})
        else:
            # 验证密码
            password_in_db = user.password  # 加密了

            password = set_password(password)
            if password_in_db != password:
                raise forms.ValidationError({'password': '密码错误'})
            else:
                cleaned_data['user']=user
                return cleaned_data

supermaker/apps/sp_user/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect, reverse
from django.utils.decorators import method_decorator

from django.views import View
from django.views.decorators.csrf import csrf_exempt

from db.base_view import BaseVerifyView
from sp_user.forms import RegisterForm, LoginForm
from sp_user.helper import verify_login_required
from sp_user.models import User


class RegisterView(View):
    def get(self, request):
        # 使用form渲染html
        form = RegisterForm()
        return render(request, 'sp_user/reg.html', {'form': form})

    def post(self, request):
        # 1.接收数据

        # 2.处理数据
        form = RegisterForm(request.POST)
        # 3.响应
        if form.is_valid():
            form.save()
            # 注册成功,跳转登录页面
            return redirect(reverse('sp_user:login'))

        # 注册失败
        return render(request, 'sp_user/reg.html', {'form': form})


# 登陆

class LoginView(View):
    def get(self, request):
        login_form = LoginForm()
        return render(request, 'sp_user/login.html', {'form': login_form})

    def post(self, request):
        # 接收处理数据
        login_form = LoginForm(request.POST)
        # 响应
        if login_form.is_valid():
            # 验证成功,保存登录标识到session
            user = login_form.cleaned_data.get('user')
            request.session['ID'] = user.pk
            request.session['phone'] = user.phone
            # 设置有效期,关闭浏览器就结束
            request.session.set_expiry(0)

            return redirect(reverse('sp_user:center'))
        # 验证失败
        return render(request, 'sp_user/login.html', {'form': login_form})


class CenterView(View):
    def get(self, request):
        phone = request.session.get('phone')
        context = {
            'phone': phone
        }
        return render(request, 'sp_user/center.html', context)

    def post(self, request):
        pass


class InfoView(BaseVerifyView):
    # 个人资料功能
    def get(self, request):
        # 验证用户是否登录
        user_id = request.session.get("ID")
        # 查询当前用户的所有信息
        user = User.objects.filter(pk=user_id).first()

        context = {
            "user": user
        }
        return render(request, "sp_user/info.html", context)

    def post(self, request):
        # 1. 接收数据
        user_id = request.session.get("ID")
        data = request.POST
        file = request.FILES['head']
        # 2. 处理数据
        # 更新用户的头像
        user = User.objects.get(pk=user_id)
        user.head = file
        user.save()
        # 3. 响应
        return redirect(reverse("sp_user:center"))

        # 单独使用一个视图函数处理图片的上传

    # 验证登录装饰器  放在 公共base里,所有需要验证的页面都需要这个
    # @method_decorator(verify_login_required)
    # def dispatch(self, request, *args, **kwargs):
    #     return super().dispatch(request,*args, **kwargs)


# 登录验证装饰器的使用 函数形式
@csrf_exempt  # 移除令牌限制
def upload_head(request):
    if request.method == "POST":
        # 获取用户的id
        user_id = request.session.get("ID")
        # 获取用户对象
        user = User.objects.get(pk=user_id)
        # 保存图片
        user.head = request.FILES['file']  # 通过键获取对应的文件
        user.save()
        return JsonResponse({"error": 0})
    else:
        return JsonResponse({"error": 1})


@verify_login_required
def info(request):
    return render(request, "sp_user/info.html")

supermaker/templates/sp_user/center.html
{% extends 'public/base_nav.html' %}
{% load static %}

{% block content_main %}
    <div style="height: 49px;"></div>
    <div class="member">
        <div class="mem-tit">{{ phone }}
            <a href="step.html" class="step"><img src="{% static 'images/step.png' %}" width="26"/></a>
        </div>
        <div class="mem-pic">
            <div class="mem-pic-bg" style="background-image: url({% static 'images/memtx.png' %});"></div>
        </div>
        <ul class="member-menu">
            <li>
                <a href="records.html">
                    <p class="yellow">0</p>
                    <p class="black">帐户余额 </p>
                </a>
            </li>
            <li>
                <a href="integral.html">
                    <p class="yellow">0</p>
                    <p class="black">积分 </p>
                </a>
            </li>
            <li>
                <a href="yhq.html">
                    <p class="yellow">0</p>
                    <p class="black">优惠劵 </p>
                </a>
            </li>
            <li>
                <a href="collect.html">
                    <p class="yellow">0</p>
                    <p class="black">我的收藏 </p>
                </a>
            </li>
        </ul>
    </div>
    <div class="user-list">
        <div class="u-list-main">
            <img src="{% static 'images/order-pic.png' %}" width="27"/>
            <span>我的购物订单</span>
            <a href="allorder.html">查看全部订单></a>
        </div>
        <ul class="user-nav">
            <li><a href="allorder.html"> <img src="{% static 'images/1-icon.png' %}">
                <p>待付款</p></a></li>
            <li><a href="allorder.html"> <img src="{% static 'images/1-icon1.png' %}">
                <p>待收货</p></a></li>
            <li><a href="allorder.html"> <img src="{% static 'images/1-icon2.png' %}">
                <p>待评价</p></a></li>
            <li><a href="allorder.html"> <img src="{% static 'images/1-icon3.png' %}">
                <p>退换货</p></a></li>
        </ul>
        <div class="u-list-main">
            <img src="{% static '' %}images/order-my.png" width="27"/>
            <span>帐户与安全</span>
        </div>
        <ul class="user-nav">
            <li><a href="{% url 'sp_user:info' %}"> <img src="{% static 'images/1-icon4.png' %}">
                <p>个人资料</p></a></li>
            <li><a href="gladdress.html"> <img src="{% static 'images/1-icon5.png' %}">
                <p>收货地址</p></a></li>
            <li><a href="saftystep.html"> <img src="{% static 'images/1-icon6.png' %}">
                <p>安全设置</p></a></li>
            <li><a href="money.html"> <img src="{% static 'images/1-icon7.png' %}">
                <p>我的钱包</p></a></li>
        </ul>
    </div>
    <!--导航-->
    <ul class="sq-nav"
        style=" background: #fff; margin-top: 1rem; border-top: 1px solid #ddd;  border-bottom: 1px solid #ddd;">
        <li>
            <div class="am-gallery-item">
                <a href="job.html" class="">
                    <img src="{% static 'images/m_03.png' %}"/>
                    <p>我要兼职</p>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="recommend.html" class="">
                    <img src="{% static 'images/m_04.png' %}"/>
                    <p>推荐有奖</p>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="myrecommend.html" class="">
                    <img src="{% static 'images/m_05.png' %}"/>
                    <p>我的推荐</p>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="" class="">
                    <img src="{% static 'images/m_06.png' %}"/>
                    <p>我的佣金</p>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="yhq.html" class="">
                    <img src="{% static 'images/m_02.png' %}"/>
                    <p>我的红包</p>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="message.html" class="">
                    <img src="{% static 'images/m_07.png' %}"/>
                    <p>我的动态</p>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="javascript:;" class="index-qd">
                    <img src="{% static 'images/m_08.png' %}"/>
                    <p>客服中心</p>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="" class="">
                    <img src="{% static 'images/m_09.png' %}"/>
                    <p>安全退出</p>
                </a>
            </div>
        </li>
    </ul>
    </div>
    <!--客服中心-->
    <div class="qd-box">
        <div class="popup-title">
            <span>客服中心</span>
            <div class="popup-close"><i class="iconfont">&#xe602</i></div>
        </div>
        <div class="dq-text">
            <a href="http://wpa.qq.com/msgrd?v=3&uin=123456789&site=qq&menu=yes">
                <img src="{% static 'images/contactqq.png' %}" width="50"/>
                <p class="contactqq">联系QQ</p>
            </a>
            <a href="tel:0791-12345678">
                <img src="{% static 'images/contacttele.png' %}" width="50"/>
                <p class="contacttele">呼叫电话</p>
            </a>
        </div>
    </div>
    <!--客服中心-->

{% endblock %}

supermaker/templates/sp_user/info.html
{% extends 'public/base.html' %}
{% load static %}

{% block meta_css %}
    <!--引入CSS-->
<link rel="stylesheet" type="text/css" href="{% static 'webuploader/webuploader.css' %}">

<!--引入JS-->
<script type="text/javascript" src="{% static 'webuploader/webuploader.js' %}"></script>
    <link href="{% static 'css/check.css' %}" rel="stylesheet" type="text/css"/>
{% endblock %}

{% block content_nav %}
    <header data-am-widget="header" class="am-header am-header-default sq-head ">
        <div class="am-header-left am-header-nav">
            <a href="javascript:history.back()" class="">
                <i class="am-icon-chevron-left"></i>
            </a>
        </div>
        <h1 class="am-header-title">
            <a href="" class="">个人资料</a>
        </h1>
    </header>
{% endblock %}

{% block content_main %}
    <div style="height: 49px;"></div>
    <ul class="safty1">
        <li>
            <a href="">
                <i style="margin-top: 25px;">头像</i>
                <div class="infor-pic">
                    <img id ="head_img" src="{{ MEDIA_URL }}{{ user.head }}"/>
                </div>
            </a>
           <!--dom结构部分-->
            <div id="uploader-demo">
                <!--用来存放item-->
                <div id="fileList" class="uploader-list"></div>
                <div id="filePicker">选择图片</div>
            </div>
        </li>
        <li>
            <a href="">
                <i>昵称</i>
                <input class="infor-tele" placeholder="默契"/>
            </a>
        </li>
        <li>
            <a href="">
                <i>性别</i>
                <i class="infor-tele">
                    <label class="am-radio-inline">
                        <input type="radio" name="radio10" checked="checked" value="1" data-am-ucheck>男
                    </label>
                    <label class="am-radio-inline">
                        <input type="radio" name="radio10" value="1" data-am-ucheck>女
                    </label>
                </i>
            </a>
        </li>
        <li>
            <a href="">
                <i>生日</i>
                <input class="infor-tele" placeholder="出生日期"/>
            </a>
        </li>
    </ul>
    <div style="height: 10px; background: #efefef;"></div>
    <ul class="safty1">
        <li>
            <i>学校</i>
            <input class="infor-tele" placeholder="就读于哪个学校"/>
        </li>
        <li>
            <i>位置</i>
            <input class="infor-tele" placeholder="详细地址"/>
        </li>
        <li>
            <i>故乡</i>
            <input class="infor-tele" placeholder="来自哪里"/>
        </li>
        <li>
            <i>手机</i>
            <input class="infor-tele" placeholder="13012345678"/>
        </li>
    </ul>


{% endblock %}



{% block footer_js %}
    <script>
        // 初始化Web Uploader
        var uploader = WebUploader.create({

            // 选完文件后，是否自动上传。
            auto: true,

            // swf文件路径
            swf: "{% static 'webuploader/Uploader.swf' %}",

            // 文件接收服务端。
            server: '文件接收的服务器的地址',

            // 选择文件的按钮。可选。
            // 内部根据当前运行是创建，可能是input元素，也可能是flash.
            pick: '#filePicker',

            // 只允许选择图片文件。
            accept: {
                title: 'Images',
                extensions: 'gif,jpg,jpeg,bmp,png',
                mimeTypes: 'image/*'
            }
        });


        // 当有文件添加进来的时候
        uploader.on('fileQueued', function (file) {
            $img = $("#head_img");
            // 创建缩略图
            // 如果为非图片文件，可以不用调用此方法。
            // thumbnailWidth x thumbnailHeight 为 100 x 100
            uploader.makeThumb(file, function (error, src) {
                $img.attr('src', src);
            }, 100, 100);
        });
    </script>
{% endblock %}

supermaker/templates/sp_user/login.html
{% extends 'public/base.html' %}
{% load static %}
{% block meta_css %}
    <style>
        .errornote {
            color: red;
        }
    </style>
{% endblock %}
{% block content_main %}
    <header data-am-widget="header" class="am-header am-header-default sq-head ">
        <div class="am-header-left am-header-nav">
            <a href="javascript:history.back()" class="">
                <i class="am-icon-chevron-left"></i>
            </a>
        </div>
        <h1 class="am-header-title">
            <a href="" class="">登录</a>
        </h1>
    </header>
    <div style="height: 49px;"></div>

    <div style="height: 3rem;"></div>

    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form.phone }}
        <p class="errornote">{{ form.errors.phone.0 }}</p>
        {{ form.password }}
        <p class="errornote">{{ form.errors.password.0 }}</p>
        <input type="submit" class="login-btn" value="我要登录">
    </form>

    <div class="agree">
        <a href="{% url 'sp_user:register' %}">免费注册</a>
        <a href="forgetpassword.html" class="forget">忘记密码？</a>
    </div>
    <div class="line"></div>
    <div class="line-text">第三方账号登录</div>
    <ul class="second-login">
        <li><a href=""><img src="{% static 'images/wxlogin.png' %}"/></a></li>
        <li><a href=""><img src="{% static 'images/qqlogin.png' %}"/></a></li>
        <li><a href=""><img src="{% static 'images/sinalog.png' %}"/></a></li>
    </ul>
{% endblock %}

supermaker/templates/sp_user/reg.html
{% extends "public/base.html" %}
{% load static %}

{% block content_nav %}
    <header data-am-widget="header" class="am-header am-header-default sq-head ">
        <div class="am-header-left am-header-nav">
            <a href="javascript:history.back()" class="">
                <i class="am-icon-chevron-left"></i>
            </a>
        </div>
        <h1 class="am-header-title">
            <a href="" class="">注册</a>
        </h1>
    </header>
{% endblock %}

{% block content_main %}
    <div style="height: 49px;"></div>

    <div style="height: 3rem;"></div>
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form.phone }}<p class="am-text-danger">{{ form.errors.phone.0 }}</p>
        {{ form.password }}<p class="am-text-danger">{{ form.errors.password.0 }}</p>
        <input type="password" name="repassword" placeholder="确认密码" class="login-name">
        <div class="yzm" style="margin-top: 1.5rem;">
            <input type="text" name="verify_code" class="reg-yzm" placeholder="输入验证码"/>
            <input type="button" class="yzm-hq" value="获取验证码"/>
        </div>
        <p class="am-text-danger">{{ form.errors.verify_code.0 }}</p>
        <input type="submit" class="login-btn" value="立即注册">
        <div class="agree">
            <input type="checkbox" name="agree" value="1" checked="">&nbsp;同意
            <p class="am-text-danger">{{ form.errors.agree.0 }}</p>
            <a href="" class="xy">《用户协议》</a>
            <div class="r-login">已有账号，请
                <a href="{% url 'sp_user:login' %}" class="l-login">登录</a>
            </div>
        </div>
    </form>

{% endblock %}